### ISSUE TITLE
Removed tag v1.0.1 breaking composer install

### ISSUE THREAD

**Issue by planetahuerto** [BitBagCommerce/SyliusAdyenPlugin#55]

**Comment by RaulColomaPH** [comment]
Please, fix this [packagist](https://packagist.org/packages/bitbag/adyen-plugin) to the correct repository resource.
It will point to the SyliusAdyenPlugin_old Github repo

**Comment by KrisFlorq** [comment]
I don't know if I understand you correctly, we didn't made a new release of the old plugin. This plugin is a new repository with a different packagist entry: https://packagist.org/packages/bitbag/sylius-adyen-plugin.
The one that you mentioned above links to the old one. We had an error in the installation guide as the composer require was showing the old package name : bitbag/adyen-plugin

I know that that this might be a bit confusing with the naming but I hope that this helps.

**Comment by RaulColomaPH** [comment]
Thank's for fix the [packagist](https://packagist.org/packages/bitbag/adyen-plugin) entry, now point to the correct github [repository](https://github.com/BitBagCommerce/SyliusAdyenPlugin_old)
