### ISSUE TITLE
Installation Error - grid filter of type "log_level" already exists

### ISSUE THREAD

**Issue by Ferror** [BitBagCommerce/SyliusAdyenPlugin#63]
Hi, I tried to install the plugin via the installation guide and got this error:
```
The controller for URI "/en_US/_partial/cart/summary" is not callable: grid filter of type "log_level" already exists.
```

Then I tried to hide the summary partial, but with no luck. Do you mind checking out my PR and see if I missed something?

The Project has Docker so you will be able to run :)

**Comment by jakub-groncki** [comment]
Hi @Ferror,

I can't see your PR though. How did you stumble upon this problem?

**Comment by Ferror** [comment]
@jakub-groncki Sorry. I must have forgotten to make it as a link. https://github.com/Sylius/SyliusSalesDemo/pull/12

**Comment by jakub-groncki** [comment]
@Ferror the PR looks ok. Looks like there's some name clashing between the Adyen and Mollie integrations regarding one of the grids. Would you mind checking out the fix and confirming if it's ok?

**Comment by Ferror** [comment]
@jakub-groncki it works :)

**Comment by jakub-groncki** [comment]
Great :)

**Comment by jakub-groncki** [comment]
v1.1.1 contains the fix :)

**Comment by Ferror** [comment]
@jakub-groncki seems like it's not ready yet in packagist :(
