### ISSUE TITLE
Live endpoint URL prefix	 not working

### ISSUE THREAD

**Issue by fabiolor** [BitBagCommerce/SyliusAdyenPlugin#67]
Switching from Test to Live environment gives an error.

`request.CRITICAL: Uncaught PHP Exception Adyen\AdyenException: "Please provide your unique live url prefix on the setEnvironment() call on the Client or provide endpointCheckout in your config object." at ---/vendor/adyen/php-api-library/src/Adyen/Service/AbstractCheckoutResource.php line 23 {"exception":"[object] (Adyen\\AdyenException(code: 0): Please provide your unique live url prefix on the setEnvironment() call on the Client or provide endpointCheckout in your config object. at ---/vendor/adyen/php-api-library/src/Adyen/Service/AbstractCheckoutResource.php:23)"}`

Adyen PHP library needs the "Live Endpoint URL prefix" to be passed as second parameter (function `setEnvironment()` in `CLient.php`), but the SyliusAdyenPlugin plugin does not.
In `AdyenTransportFactory.php` the `setEnvironment()` method is always called with one parameter.

```php
        $client->setEnvironment(
            $options['environment'] == AdyenClientInterface::TEST_ENVIRONMENT
                ? Environment::TEST
                : Environment::LIVE
        );
```

**Comment by developerlover** [comment]
Hi guys, any update on this? Thank you!

**Comment by pbalcerzak** [comment]
Hi, we are working on it

**Comment by developerlover** [comment]
Thank you so much! :)

**Comment by pbalcerzak** [comment]
v1.2.1 contains the fix :)
