### ISSUE TITLE
Impossible to process payment

### ISSUE THREAD

**Issue by Roshyo** [BitBagCommerce/SyliusAdyenPlugin#74]
When I try to submit the payment, the AJAX call ends in 500 error:

![image](https://user-images.githubusercontent.com/9363039/194884969-6d3570ae-ece1-4682-a859-677a2eec5c66.png)

And if we inspect the request, it seems all data are stored in `$request->getContent()` instead of `$request->request->all()`

![image](https://user-images.githubusercontent.com/9363039/194885195-03e7b123-a882-43b9-9363-c98c822109d0.png)

![image](https://user-images.githubusercontent.com/9363039/194885252-efb1baf6-9c0e-4353-b3db-4ef01a264b62.png)

**Comment by pbalcerzak** [comment]
Hi @Roshyo, I'll look at this tomorrow morning

**Comment by pbalcerzak** [comment]
Closing as it has been resolved on slack
