### ISSUE TITLE
Sylius v1.12 (Symfony 6 support)

### ISSUE THREAD

**Issue by juniorsk** [BitBagCommerce/SyliusAdyenPlugin#78]
Hi!
Any plans on supporting Sylius v1.12 (Symfony 6)?

**Comment by jtonia** [comment]
Hello!

Yes, it's in the plans.

Would it be possible for you to share anything more regarding your request?

**Comment by loevgaard** [comment]
Can you share some light on the support of 1.12? :)

**Comment by rafalmal** [comment]
Support for sylius 1.12 and symfony 6 has been implemented.
