### ISSUE TITLE
Allow administrator to set payment method from admin

### ISSUE THREAD

**Issue by loevgaard** [BitBagCommerce/SyliusAdyenPlugin#80]
It would be nice to allow the administrator to create specific Adyen payment methods in the backend, so you can display the payment step as so:

<img width="1385" alt="image" src="https://user-images.githubusercontent.com/2412177/223435671-619ed4b0-6ea6-4893-baa4-f43e11b89d07.png">

Then when you hit the confirm page you know which payment method the customer selected and you show the relevant widget for that payment method.

**Comment by MacBalc** [comment]
@loevgaard seems like neat idea. However implementing such feature would require extensive work which at current point is already done heavily by adyen sdk.
