### ISSUE TITLE
Credit card input doesn't allow special characters

### ISSUE THREAD

**Issue by loevgaard** [BitBagCommerce/SyliusAdyenPlugin#81]
When I try to input my name 'Joachim Løvgaard' it won't let me input 'ø'.

<img width="567" alt="image" src="https://user-images.githubusercontent.com/2412177/225883792-074b0728-302a-4ba8-90ba-6bf60d4a80be.png">

**Comment by MacBalc** [comment]
@loevgaard PR should fix described issue
